### ISSUE TITLE
feat: Implement the comment interaction

### ISSUE THREAD

**Issue by BioPhoton** [push-based/user-flow-gh-action#10]
# Motivation 
To inform the user about user flow results.
This issue focuses on informing the developer in a comment on the current PR.

This logic does not include the content generation of the comment.

## Implementation

**Steps:**
- research existing GH actions
- POC in separate GH action
- specify the behavior
- detail research 
  - reuse GH actions in GH actions
  - exporting to json report to md from user-flow

## Research existing GH actions

- https://github.com/marketplace/actions/create-update-comment-on-pull-request
- https://github.com/marketplace/actions/sticky-pull-request-comment (winner)

## POC in separate GH action 

https://github.com/push-based/user-flow/pull/81

## Specify the behavior

Discussion: 
- hide vs delete => benefit of hide is the history downside is the pollution of comments after every commit

**Generate the report**
- create a reduced report as `json` and `md`.  (`-f md -f json`)
  command: 
```
user-flow collect [custom-config-options] [action-related-options]  
user-flow collect --rcPath .user-flowrc.ci.json -f md -f json  
```
- save user specific formats
- save additional `user-flow-report.json` in the PR (because we need it as base data for the comparison)
- handle the reduced report as comment in the PR
- delete `user-flow-report.md` file

**handle the reduced report as comment in the PR**
- If there is no comment ? create a initial comment : 
  - hide the previous created comment &&
    - and add a new comment at the end
  
<img width="681" alt="user-flow--report-visulaization" src="https://user-images.githubusercontent.com/10064416/199785870-aa6683d3-45c5-47e7-b953-0a927c4bc70a.PNG">

# Action Interface

## Example `yaml`

[sticky-pull-request-comment feature](https://github.com/marketplace/actions/sticky-pull-request-comment#hide-the-previous-comment-and-add-a-comment-at-the-end)

```yaml
name: user-flow
# @TODO
on:
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  user-flow-integrated-in-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm i
      - name: user-flow ci test
        run: npm run run-user-flows-and-persist-data 
      - name: Add reduced report as comment to the PR 
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          path: ./packages/user-flow-ci-integration/measures/order-coffee-in-ci.uf.md
```

## GitHub action parameters 

**Params**
-  `rcPath` -  e.g. `.user-flowrc.ci.json`

**Default Setup**
```yaml
    # ... 
    - name: Add reduced report as comment to the PR 
        uses: push-based/user-flow-gh-action@v1
```

**Setup with parameters**
```yaml
    # ... 
    - name: Add reduced report as comment to the PR 
        uses: push-based/user-flow-gh-action@v1
        with:
          rcPath: .user-flowrc.ci.json
```

# Related #80
